// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IProductsFields {
  /** id */
  id: number;

  /** Name */
  name: string;

  /** Image_url */
  image_url: string;

  /** Price */
  price: number;

  /** Description */
  description: string;

  /** Url */
  url: string;

  /** Slug */
  slug: string;
}

export interface IProducts extends Entry<IProductsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "products";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE = "products";

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
